### ISSUE TITLE
405 (Method Not Allowed) PUT

### ISSUE THREAD

**Issue by ricardodebeijer** [bell345/real-randomizer#1]
Hello,

I have been using this tool weekly for years with great pleasure, but recently something changed/broke (on Spotify's side I think):

When clicking the "Make Playlist" button, I get an error:
`PUT 405 (Method Not Allowed)`, on the `clearPlaylist` method.

![image](https://github.com/bell345/real-randomizer/assets/4396694/94ab4c83-9133-4865-8b14-0e210feb4b13)

![image](https://github.com/bell345/real-randomizer/assets/4396694/c31779b2-7470-4d83-82c7-01e029d9c0f9)

It would be great if you can look into this

**Comment by bell345** [comment]
Oh hey, thank you for using my ancient web app! It seems that, in the nearly 8 years since I looked at the implementation, the Spotify API has been updated such that the endpoints for listing and viewing playlists have remained the same, but endpoints for editing playlists have changed. I'm going to implement the API changes soon so I can get this back up and running again.

**Comment by bell345** [comment]
Hey @ricardodebeijer; everything should be good now. I've pushed a new Docker image, updated my website with the newest version, and tested that I can create playlists. Let me know if it works for you.

**Comment by ricardodebeijer** [comment]
Yes, pulled the latest version and now the playlist is created.
Thanks for the quick fix 👍
